Authentication/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('sing_up/', views.sing_up, name='sing_up'),
    path('login/', views.Loginview.as_view(), name='user_login'),
    path('profile/Update', views.UpdateView.as_view(), name='Profile_update'),
    path('profile/password_change/', views.pass_change, name='pass_change'),
    path('logout/', views.user_logout, name='user_logout'),
    path('profile/', views.profile, name='profile'),
    path('contact/', views.contact_view, name='contact'),
    path('email_verification/<str:uidb64>/<str:token>/', views.EmailVerificationView.as_view(), name='email_verification'),
 
]

Pet_Adoption_Platform/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name = 'home'),
    path('home/', views.home, name = 'home'),
    path('pet_category/<slug:pet_slug>/', views.all_pet, name='pet_wise_post'),
    path('', include('Authentication.urls')),
    path('', include('pet.urls')),
    path('', include('buy.urls')),
    path('contact/',views.contact, name='contact'),
    path('about/',views.about, name='about'),
    path('all_pet/',views.all_pet, name='all_pet'),
    path('pet_details/<int:id>', views.Details.as_view(), name='Details')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

buy/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('adopt/<int:id>/', views.adopt, name='adopt'),
    path('adopt_history',views.adopt_history,name='adopt_history'),
    path('Basic_subscribe/', views.subscribe_1, name='basic_subscribe'),
    path('Basic_subscribe_history/', views.subscribe_info, name='subscribe_his'),
    path('Standard_subscribe/',views.subscribe_2, name = 'standard_subscribe'),
    path('Premium_subscribe/',views.subscribe_3, name = 'premium_subscribe'),
    path('paypal-return/<str:subscription_type>/', views.paypal_return, name='paypal_return'),
    path('paypal-cancel/<str:subscription_type>/', views.paypal_cancel, name='paypal_cancel'),
     path('paypal-return/adopt/<int:id>/', views.paypal_return, {'subscription_type': 'adopt'}, name='paypal_return'),
    path('paypal-cancel/adopt/<int:id>/', views.paypal_cancel, {'subscription_type': 'adopt'}, name='paypal_cancel'),

]

Authentication/models.py
from django.db import models

# Create your models here.
class ContactMessage(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.name

buy/models.py
from django.db import models
from django.contrib.auth.models import User
from pet.models import pets

# Create your models here.
month = [('1','1'),('2','2'),('3','3'),('4','4'),('5','5'),('6','6'),('7','7'),('8','8'),('9','9'),('10','10')]
subscription_choices = [
        ('Basic', 'Basic'),
        ('Standard', 'Standard'),
        ('Premium', 'Premium'),
        # Add more subscription types if needed
    ]

class Adopt(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    a_pets = models.ForeignKey(pets, on_delete=models.CASCADE,null=True)
    adopt_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.user.username
    
class Subscription1(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subcribe_price = models.IntegerField(default=49)
    subscription = models.CharField(default='Basic', choices=subscription_choices, max_length=20)
    Month = models.IntegerField(choices=[(i, str(i)) for i in range(1, 13)])            
    subscription_date = models.DateField(auto_now_add=True)
    def __str__(self):
        return self.user.username
    
class Subscription2(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subcribe_price = models.IntegerField(default=99)
    subscription = models.CharField(default='Standard', choices=subscription_choices, max_length=20)
    Month = models.IntegerField(choices=[(i, str(i)) for i in range(1, 13)])
    subscription_date = models.DateField(auto_now_add=True)
    def __str__(self):
        return self.user.username

    
class Subscription3(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subcribe_price = models.IntegerField(default=149)
    subscription = models.CharField(default='Premium', choices=subscription_choices, max_length=20)
    Month = models.IntegerField(choices=[(i, str(i)) for i in range(1, 13)])
    subscription_date = models.DateField(auto_now_add=True)
    def __str__(self):
        return self.user.username
    
class Basic_subscription_history(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    a_subscription = models.ForeignKey(Subscription1, on_delete=models.CASCADE,null=True)
    adopt_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.user.username

Authentication/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from .models import ContactMessage


class SingForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'id':'required'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'id':'required'}))

    class Meta:
        model = User
        fields = ['username','first_name','last_name','email']
        
    def save(self, commit=True):
            our_user = super().save(commit=False) # ami database e data save korbo na ekhn
            if commit == True:
                our_user.save() # user model e data save korlam
                return our_user
            return our_user

class ChangeUserForm(UserChangeForm):
    password = None
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactMessage
        fields = ['name', 'email', 'message']

Authentication/views.py
from django.shortcuts import render,redirect
from . import forms
from django.contrib import messages
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.views import View
from .forms import ChangeUserForm
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode , urlsafe_base64_decode
from django.utils.encoding import force_bytes,force_str
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from pet.models import pets
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import ContactForm
from django.core.mail import send_mail
from django.conf import settings 

from .forms import ContactForm


# Create your views here.
def sing_up(request):
    if request.method == 'POST':
        sing_up_form = forms.SingForm(request.POST)
        if sing_up_form.is_valid():
            user = sing_up_form.save()
            user.is_active = False
            user.save()

            # Send email verification
            current_site = get_current_site(request)
            subject = 'Activate Your Account'
            message = render_to_string('Authentication/veryfication_mail.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })
            user.email_user(subject, message)

            messages.success(request, 'Account Created Successfully. Please check your email to activate your account.')
            return redirect('user_login')

    else:
        sing_up_form = forms.SingForm()
    return render(request, 'sing.html', {'form': sing_up_form})

class EmailVerificationView(View):
    def get(self, request, uidb64, token):
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            messages.success(request, 'Email verification successful. You can now log in.')
        else:
            messages.error(request, 'Email verification failed.')
        return redirect('user_login')


class Loginview(LoginView):
    template_name = 'login.html'
    def get_success_url(self):
        return reverse_lazy('profile')
    def form_valid(self, form):
        messages.success(self.request, 'Logged in Successful')
        return super().form_valid(form)
    def form_invalid(self, form):
        messages.warning(self.request, 'Logged in information incorrect')
        return super().form_invalid(form)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['type'] = 'Login'
        return context

# For Logout
@login_required
def user_logout(request):
    logout(request)
    messages.success(request,'Logged Out Successfully')
    return redirect('user_login')

# For Profile
@login_required
def profile(request):
    return render(request,'Authentication/profile.html' )


class UpdateView(View,LoginRequiredMixin):
    template_name = 'Authentication/profile_update.html'

    def get(self, request):
        form = ChangeUserForm(instance=request.user)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = ChangeUserForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Profile Updated Successfully')
            return redirect('profile')  # Redirect to the user's profile page
        return render(request, self.template_name, {'form': form})
    
@login_required
def pass_change(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Password Updated Successfully')
            update_session_auth_hash(request, form.user)
            return redirect('profile')
    
    else:
        form = PasswordChangeForm(user=request.user)
    return render(request, 'Authentication/pass_change.html', {'form' : form})


def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            
            # Send email
            send_mail(
                'Message from Website',
                f'Name: {name}\nEmail: {email}\nMessage: {message}',
                settings.EMAIL_HOST_USER,
                ['mdshifat.official.05@gmail.com'],
                fail_silently=False,
            )
            return redirect('contact')  # Redirect to a success page
    else:
        form = ContactForm()
    
    return render(request, 'contact.html', {'C_form': form})

Authentication/templates/Authentication/adopt_history.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/card.css' %}">
{% comment %} {% endblock %} {% block css %} {% endcomment %}
<style>
    /* Body and General Styling */
    .review-card {
        font-family: 'Montserrat', sans-serif;
        background: linear-gradient(to right, #f1f2f6, #dfe4ea);
        margin: 0 auto;
        padding: 0;
    }

    .custom-wrapper {
        max-width: 1200px;
        margin: 0 auto; /* Center the content horizontally */
        padding: 50px;
        padding-bottom: 90px;
    }

    h1 {
        font-size: 42px;
        color: #2f3640;
        text-align: center;
        margin-bottom: 40px;
        font-weight: 800;
    }
  
</style>
{% endblock %}

{% block content %}


<div class="col-12">
    <div class="review-card">
        <div class="custom-wrapper">
            <h1>Adopt History</h1>
            <div class="d-flex justify-content-center align-items-center gap-3 flex-wrap p-2">
                {% for post in dataa %}
                <div class="card shadow pet-card" style="width: 19rem;">
                    <div>
                        <img src="{{post.a_pets.image.url}}" class="card-img-top" alt="Pet Image" style="height:160px">
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">
                            <a class="btn p-1 pet-name btn-warning" href="">{{post.a_pets.name}}</a>
                        </h5>
                        <p class="card-title">{{post.a_pets.discription | truncatewords:11}}</p>
                        <h5 class="card-title price" style="position: relative; bottom: 18px;">Price: ${{post.a_pets.price}}</h5>
                        <p class="type">
                            <span style="font-weight: 600;">Pet Type:</span>
                            <button class="btn btn-danger p-0 m-0" style="margin-left: 5px;">{{ post.a_pets.pet_type }}</button>
                        </p>
                        <p class="card-title adopt-date d-flex" style="position: relative; bottom: 25px;">
                            <span style="font-weight: 600;">Adopt Date:</span>
                            <span style="margin-left: 5px;">{{ post.adopt_date }}</span>
                        </p>
                        <div class='btnn'>
                            <a class="btn btn-danger m-2" style="position: relative; top: 25px;" href="{% url 'Details' post.a_pets.id %}">Review</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% include "fotter.html" %}
{% endblock %}

Authentication/templates/Authentication/pass_change.html
{% extends "base.html" %}
{% load static %}

{% block css %}
<!-- Font Icon -->
<link rel="stylesheet" href="{% static "css/fonts/material-icon/css/material-design-iconic-font.min.css" %}">

<!-- Main css -->
<link rel="stylesheet" href="{% static "css/sing.css" %}">
{% endblock  %}

{% block content %}
<div class="main">
    <section class="sign-in">
        <div class="container">
            <div class="signin-content">
                <!-- ... your existing login form ... -->

                <div class="signin-form">
                    <h2 class="form-title">Change Password</h2>
                    <form method="post" class="register-form" id="password-change-form" >
                        {% csrf_token %}
                        {{ form.old_password.errors }}
                        {{ form.new_password1.errors }}
                        {{ form.new_password2.errors }}

                        <div class="form-group">
                            <label for="{{ form.old_password.id_for_label }}"><i class="zmdi zmdi-lock"></i></label>
                            <input type="password" name="{{ form.old_password.name }}" id="{{ form.old_password.id_for_label }}" placeholder="Old Password" required/>
                        </div>
                        <div class="form-group">
                            <label for="{{ form.new_password1.id_for_label }}"><i class="zmdi zmdi-lock"></i></label>
                            <input type="password" name="{{ form.new_password1.name }}" id="{{ form.new_password1.id_for_label }}" placeholder="New Password" required/>
                        </div>
                        <div class="form-group">
                            <label for="{{ form.new_password2.id_for_label }}"><i class="zmdi zmdi-lock"></i></label>
                            <input type="password" name="{{ form.new_password2.name }}" id="{{ form.new_password2.id_for_label }}" placeholder="Confirm New Password" required/>
                        </div>
                        <div class="form-group form-button">
                            <input type="submit" name="change-password" id="change-password" class="form-submit" value="Change Password"/>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
</div>
{% include "fotter.html" %}

{% endblock  %}

Authentication/templates/Authentication/profile.html
{% extends "base.html" %} {% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">
{% endblock  %}

{% block content %}

<div class="col-12">
  <div class="card m-2">
    <div class="card-body four">
      <div class="container">
        <div class="main-body">
          <!-- Breadcrumb -->
          <nav aria-label="breadcrumb" class="main-breadcrumb">
            <ol class="breadcrumb">
              <h class="breadcrumb-item active" aria-current="page"
                >User Profile</h
              >
            </ol>
          </nav>
          <!-- /Breadcrumb -->

          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div
                    class="d-flex flex-column align-items-center text-center"
                  >
                    <img
                      src="https://bootdey.com/img/Content/avatar/avatar7.png"
                      alt="Admin"
                      class="rounded-circle"
                      width="150"
                    />
                    <div class="mt-3">
                      <h4>{{ user.first_name }} {{ user.last_name }}</h4>
                      
                      <p class="text-muted font-size-sm">{{ user.email }}</p>
                      <div class="d-flex">
                        <a
                          class="btn btn-warning text-dark"
                          aria-current="page"
                          href="{% url 'pass_change' %}"
                          >Update Password</a
                        >
                        <a
                          class="mx-1 btn btn-warning text-dark"
                          href="{% url 'adopt_history' %}"
                          >Adopt History</a
                        >
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">User Name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ user.username }}
                    </div>
                  </div>
                  <hr />
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">First Name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{user.first_name}}
                    </div>
                  </div>
                  <hr />
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Last Name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{user.last_name}}
                    </div>
                  </div>
                  <hr />
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Email</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">{{user.email}}</div>
                  </div>
                  <hr />
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Phone</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">(239) 816-9029</div>
                  </div>
                  <hr />

                  <hr />
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Address</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      Bay Area, San Francisco, CA
                    </div>
                  </div>
                  <hr />

                  <div class="row">
                    <div class="col-md-8">
                        <a class="mx-3 btn btn-warning text-dark" aria-current="page" href="{% url 'Profile_update' %}">Edit</a>
                    </div>
                    <div class="col-md-4 mt-3 mt-md-0">
                        <a class="mx-3 btn btn-primary text-white" aria-current="page" href="{% url 'subscribe_his' %}">Subscription History</a>
                    </div>
                </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>



{% include "fotter.html" %} {% endblock %}

Authentication/templates/Authentication/profile_update.html
{% extends "base.html" %}
{% load static %}

{% block css %}
<!-- Font Icon -->
<link rel="stylesheet" href="{% static "css/fonts/material-icon/css/material-design-iconic-font.min.css" %}">

<!-- Main css -->
<link rel="stylesheet" href="{% static "css/sing.css" %}">
{% endblock  %}

{% block content %}
<div class="main s-body">
    <section class="signup">
        <div class="container">
            <div class="signup-content">
                <div class="signup-form">
                    <h2 class="form-title">Profile Update</h2>
                    <form method="post" class="register-form" id="update-profile-form">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        
                        {% for hidden_field in form.hidden_fields %}
                            {{ hidden_field }}
                        {% endfor %}

                        <div class="form-group">
                            <label for="{{ form.username.id_for_label }}"><i class="zmdi zmdi-account material-icons-name"></i></label>
                            {{ form.username }}
                            {% if form.username.errors %}
                                {% for error in form.username.errors %}
                                    <p class="text-danger m-auto pb-2">{{ error }}</p>
                                {% endfor %}
                            {% endif %}
                        </div>

                        <div class="form-group">
                            <label for="{{ form.first_name.id_for_label }}"><i class="zmdi zmdi-account material-icons-name"></i></label>
                            {{ form.first_name }}
                            {% if form.first_name.errors %}
                                {% for error in form.first_name.errors %}
                                    <p class="text-bg-danger m-auto pb-2">{{ error }}</p>
                                {% endfor %}
                            {% endif %}
                        </div>

                        <div class="form-group">
                            <label for="{{ form.last_name.id_for_label }}"><i class="zmdi zmdi-account material-icons-name"></i></label>
                            {{ form.last_name }}
                            {% if form.last_name.errors %}
                                {% for error in form.last_name.errors %}
                                    <p class="text-bg-danger m-auto pb-2">{{ error }}</p>
                                {% endfor %}
                            {% endif %}
                        </div>

                        <div class="form-group">
                            <label for="{{ form.email.id_for_label }}"><i class="zmdi zmdi-email"></i></label>
                            {{ form.email }}
                            {% if form.email.errors %}
                                {% for error in form.email.errors %}
                                    <p class="text-danger m-auto pb-2">{{ error }}</p>
                                {% endfor %}
                            {% endif %}
                        </div>

                        <div class="form-group">
                            <label for="{{ form.password1.id_for_label }}"><i class="zmdi zmdi-lock"></i></label>
                            {{ form.password1 }}
                            {% if form.password1.errors %}
                                {% for error in form.password1.errors %}
                                    <p class="text-danger m-auto pb-2">{{ error }}</p>
                                {% endfor %}
                            {% endif %}
                        </div>

                        <div class="form-group">
                            <label for="{{ form.password2.id_for_label }}"><i class="zmdi zmdi-lock-outline"></i></label>
                            {{ form.password2 }}
                            {% if form.password2.errors %}
                                {% for error in form.password2.errors %}
                                    <p class="text-danger m-auto pb-2">{{ error }}</p>
                                {% endfor %}
                            {% endif %}
                        </div>

                        <div class="form-group">
                            <input type="submit" name="update_profile" id="update_profile" class="form-submit" value="Update Profile"/>
                        </div>
                    </form>
                </div>
                <div class="signup-image">
                    <figure><img src="{% static "images/signup-image.jpg" %}" alt="sign up image"></figure>
                    
                </div>
            </div>
        </div>
    </section>
</div>

{% include "fotter.html" %}
{% endblock %}

Authentication/templates/Authentication/subscribe.html
{% extends 'base.html' %}
{% block content %}
<div class="container d-flex justify-content-center align-items-center vh-100">
    <div class="card shadow-lg" style="width: 40rem; border-radius: 15px;">
        <div class="card-body">
            <h2 class="card-title text-center mb-4">Subscribe Now</h2>
            <p class="text-muted text-center mb-4">Choose your subscription duration and proceed with payment</p>
            
            <form method="post" id="subscribeForm">
                {% csrf_token %}
                <!-- Select Month -->
                <div class="form-group mb-4">
                    <label for="id_Month" class="form-label fw-bold">Select Duration (Months)</label>
                    {{ subscribe_form.Month }}
                </div>

                <!-- PayPal Button -->
                <div class="d-grid">
                    <button type="submit" class="btn btn-warning btn-lg">
                        <i class="fas fa-check-circle me-2"></i> Proceed to Payment
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- PayPal JavaScript SDK -->




{% endblock %}

Authentication/templates/Authentication/subscribe_history.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/table.css' %}">
{% endblock %}


{% block content %}
<div class="history-container">
  <div class="header">
    <h1>Subscription History</h1>
    <p>Review your subscription details, pricing, and status below.</p>
  </div>

  <div class="subscriptions-table">
    <table>
      <thead>
        <tr>
          <th>Plan Name</th>
          <th>Price (USD)</th>
          <th>Months</th>
          <th>Total Paid</th>
          <th>Subscription Date</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        {% for key, value in datas.items %}
          {% for history in value %}
            <tr>
              <td class="highlight">{{ history.subscription }}</td>
              <td>${{ history.subcribe_price }}</td>
              <td>{{ history.Month }}</td>
              <td>${{ history.result }}</td>
              <td>{{ history.subscription_date }}</td>
              <td>
                {% comment %} {% if history.status == 'active' %} {% endcomment %}
                  <span class="status-active">Active</span>
                {% comment %} {% else %}
                  <span class="status-expired">Expired</span>
                {% endif %} {% endcomment %}
              </td>
            </tr>
          {% endfor %}
        {% endfor %}
      </tbody>
    </table>
  </div>

  <div class="summary-section">
    <div class="summary-item">
      <h3>${{ total_spent }}</h3>
      <p>Total Spent</p>
    </div>
    <div class="summary-item">
      <h3>{{ active_subscriptions }}</h3>
      <p>Active Subscriptions</p>
    </div>
    <div class="summary-item">
      <h3>{{ expired_subscriptions }}</h3>
      <p>Expired Subscriptions</p>
    </div>
  </div>

  <div class="footer-link">
    <p>Need help? <a href="#">Contact Support</a></p>
  </div>
</div>

{% include "fotter.html" %}
{% endblock %}

Authentication/templates/Authentication/veryfication_mail.html
Hello {{ user.username }},

Thank you for signing up. Please click on the following link to activate your account:

http://{{ domain }}{% url 'email_verification' uidb64=uid token=token %}